/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
    ],
  },
  async redirects() {
    return [
      { source: '/self-love', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/self-love/:path*', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/positive-affirmations', destination: '/affirmations/positive-affirmations', permanent: true },
      { source: '/positive-affirmations/:path*', destination: '/affirmations/positive-affirmations', permanent: true },
      { source: '/daily-affirmations', destination: '/affirmations/daily-affirmations', permanent: true },
      { source: '/daily-affirmations/:path*', destination: '/affirmations/daily-affirmations', permanent: true },
      { source: '/morning-affirmations', destination: '/affirmations/morning-affirmations', permanent: true },
      { source: '/morning-affirmations/:path*', destination: '/affirmations/morning-affirmations', permanent: true },
      { source: '/money-affirmations', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/money-affirmations/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/affirmations-for-anxiety', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/affirmations-for-anxiety/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/affirmations-for-women', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/affirmations-for-women/:path*', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/relationship-affirmations', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/relationship-affirmations/:path*', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/meditation/meditation-for-beginners', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-beginners/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/types-of-meditation', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/types-of-meditation/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-sleep', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-sleep/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-in-bed', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-for-anxiety', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-with-crystals', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/best-time-to-meditate', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/mindfulness', destination: '/affirmations', permanent: true },
      { source: '/mindfulness/:path*', destination: '/affirmations', permanent: true },
      { source: '/goals', destination: '/affirmations', permanent: true },
      { source: '/goals/:path*', destination: '/affirmations', permanent: true },
      { source: '/gratitude', destination: '/affirmations', permanent: true },
      { source: '/gratitude/:path*', destination: '/affirmations', permanent: true },
      { source: '/manifestation', destination: '/affirmations', permanent: true },
      { source: '/manifestation/:path*', destination: '/affirmations', permanent: true },
      { source: '/confidence', destination: '/affirmations', permanent: true },
      { source: '/confidence/:path*', destination: '/affirmations', permanent: true },
      { source: '/anxiety', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/anxiety/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/motivation', destination: '/affirmations', permanent: true },
      { source: '/motivation/:path*', destination: '/affirmations', permanent: true },
      { source: '/happiness', destination: '/affirmations', permanent: true },
      { source: '/happiness/:path*', destination: '/affirmations', permanent: true },
      { source: '/self-care', destination: '/affirmations', permanent: true },
      { source: '/self-care/:path*', destination: '/affirmations', permanent: true },
      { source: '/wellness', destination: '/affirmations', permanent: true },
      { source: '/wellness/:path*', destination: '/affirmations', permanent: true },
      { source: '/mental-health', destination: '/affirmations', permanent: true },
      { source: '/mental-health/:path*', destination: '/affirmations', permanent: true },
      { source: '/self-esteem', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/self-esteem/:path*', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/sleep', destination: '/affirmations', permanent: true },
      { source: '/sleep/:path*', destination: '/affirmations', permanent: true },
      { source: '/stress', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/stress/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/relationships', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/relationships/:path*', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/forgiveness', destination: '/affirmations', permanent: true },
      { source: '/forgiveness/:path*', destination: '/affirmations', permanent: true },
      { source: '/success', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/success/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/abundance', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/abundance/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/law-of-attraction', destination: '/affirmations', permanent: true },
      { source: '/law-of-attraction/:path*', destination: '/affirmations', permanent: true },
      { source: '/vision-board', destination: '/affirmations', permanent: true },
      { source: '/vision-board/:path*', destination: '/affirmations', permanent: true },
      { source: '/healing', destination: '/affirmations', permanent: true },
      { source: '/healing/:path*', destination: '/affirmations', permanent: true },
      { source: '/body-positivity', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/body-positivity/:path*', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/wp-admin/:path*', destination: '/', permanent: true },
      { source: '/wp-includes/:path*', destination: '/', permanent: true },
      { source: '/wp-json/:path*', destination: '/', permanent: true },
      { source: '/feed', destination: '/', permanent: true },
      { source: '/feed/:path*', destination: '/', permanent: true },
      { source: '/author/:path*', destination: '/about', permanent: true },
      { source: '/tag/:path*', destination: '/affirmations', permanent: true },
      { source: '/category/:path*', destination: '/affirmations', permanent: true },
      { source: '/sitemap_index.xml', destination: '/sitemap.xml', permanent: true },
      { source: '/page-sitemap.xml', destination: '/sitemap.xml', permanent: true },
    ];
  },
};

module.exports = nextConfig;
