/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
    ],
  },
  async redirects() {
    return [
      { source: '/self-love', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/self-love/:path*', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/positive-affirmations', destination: '/affirmations/positive-affirmations', permanent: true },
      { source: '/positive-affirmations/:path*', destination: '/affirmations/positive-affirmations', permanent: true },
      { source: '/daily-affirmations', destination: '/affirmations/daily-affirmations', permanent: true },
      { source: '/daily-affirmations/:path*', destination: '/affirmations/daily-affirmations', permanent: true },
      { source: '/morning-affirmations', destination: '/affirmations/morning-affirmations', permanent: true },
      { source: '/morning-affirmations/:path*', destination: '/affirmations/morning-affirmations', permanent: true },
      { source: '/money-affirmations', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/money-affirmations/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/affirmations-for-anxiety', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/affirmations-for-anxiety/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/affirmations-for-women', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/affirmations-for-women/:path*', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/relationship-affirmations', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/relationship-affirmations/:path*', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/meditation/meditation-for-beginners', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-beginners/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/types-of-meditation', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/types-of-meditation/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-sleep', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/meditation-for-sleep/:path*', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-in-bed', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-for-anxiety', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/how-to-meditate-with-crystals', destination: '/meditation/how-to-meditate', permanent: true },
      { source: '/meditation/best-time-to-meditate', destination: '/meditation/how-to-meditate', permanent: true },
      // /mindfulness now has its own hub — no redirect needed
      { source: '/goals', destination: '/affirmations', permanent: true },
      { source: '/goals/:path*', destination: '/affirmations', permanent: true },
      { source: '/gratitude', destination: '/affirmations', permanent: true },
      { source: '/gratitude/:path*', destination: '/affirmations', permanent: true },
      // /manifestation now has its own hub — no redirect needed
      { source: '/confidence', destination: '/affirmations', permanent: true },
      { source: '/confidence/:path*', destination: '/affirmations', permanent: true },
      { source: '/anxiety', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/anxiety/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/motivation', destination: '/affirmations', permanent: true },
      { source: '/motivation/:path*', destination: '/affirmations', permanent: true },
      { source: '/happiness', destination: '/affirmations', permanent: true },
      { source: '/happiness/:path*', destination: '/affirmations', permanent: true },
      { source: '/self-care', destination: '/affirmations', permanent: true },
      { source: '/self-care/:path*', destination: '/affirmations', permanent: true },
      { source: '/wellness', destination: '/affirmations', permanent: true },
      { source: '/wellness/:path*', destination: '/affirmations', permanent: true },
      { source: '/mental-health', destination: '/mindset', permanent: true },
      { source: '/mental-health/:path*', destination: '/mindset', permanent: true },
      { source: '/self-esteem', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/self-esteem/:path*', destination: '/affirmations/affirmations-for-self-love', permanent: true },
      { source: '/sleep', destination: '/affirmations', permanent: true },
      { source: '/sleep/:path*', destination: '/affirmations', permanent: true },
      { source: '/stress', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/stress/:path*', destination: '/affirmations/affirmations-for-anxiety', permanent: true },
      { source: '/relationships', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/relationships/:path*', destination: '/affirmations/relationship-affirmations', permanent: true },
      { source: '/forgiveness', destination: '/affirmations', permanent: true },
      { source: '/forgiveness/:path*', destination: '/affirmations', permanent: true },
      { source: '/success', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/success/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/abundance', destination: '/affirmations/money-affirmations', permanent: true },
      { source: '/abundance/:path*', destination: '/affirmations/money-affirmations', permanent: true },
      // /law-of-attraction now has its own hub — no redirect needed
      { source: '/vision-board', destination: '/affirmations', permanent: true },
      { source: '/vision-board/:path*', destination: '/affirmations', permanent: true },
      { source: '/healing', destination: '/affirmations', permanent: true },
      { source: '/healing/:path*', destination: '/affirmations', permanent: true },
      { source: '/body-positivity', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/body-positivity/:path*', destination: '/affirmations/affirmations-for-women', permanent: true },
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/wp-admin/:path*', destination: '/', permanent: true },
      { source: '/wp-includes/:path*', destination: '/', permanent: true },
      { source: '/wp-json/:path*', destination: '/', permanent: true },
      { source: '/feed', destination: '/', permanent: true },
      { source: '/feed/:path*', destination: '/', permanent: true },
      { source: '/author/:path*', destination: '/about', permanent: true },
      { source: '/tag/:path*', destination: '/affirmations', permanent: true },
      { source: '/category/:path*', destination: '/affirmations', permanent: true },
      { source: '/sitemap_index.xml', destination: '/sitemap.xml', permanent: true },
      { source: '/page-sitemap.xml', destination: '/sitemap.xml', permanent: true },
      { source: '/privacy-policy', destination: '/privacy', permanent: true },
      { source: '/privacy-policy/:path*', destination: '/privacy', permanent: true },
      { source: '/download', destination: '/app', permanent: true },
      { source: '/Podcast', destination: '/blog', permanent: true },
      { source: '/podcast', destination: '/blog', permanent: true },
      { source: '/Giphy', destination: '/', permanent: true },
      { source: '/AIBox', destination: '/', permanent: true },
      { source: '/gettingmagnetic', destination: '/affirmations', permanent: true },
      { source: '/levelup', destination: '/affirmations', permanent: true },
      { source: '/mindsetmile', destination: '/mindset', permanent: true },
      { source: '/selfpause', destination: '/', permanent: true },
      { source: '/selfpause/:path*', destination: '/', permanent: true },
      { source: '/best-affirmation-manifestation-apps', destination: '/affirmations/affirmation-apps', permanent: true },
      { source: '/gratitude-affirmations', destination: '/affirmations/affirmations-for-positivity', permanent: true },
      { source: '/gratitude-affirmations/:path*', destination: '/affirmations/affirmations-for-positivity', permanent: true },
      { source: '/business-affirmations', destination: '/affirmations/professional-affirmations', permanent: true },
      { source: '/business-affirmations/:path*', destination: '/affirmations/professional-affirmations', permanent: true },
      { source: '/want-your-kids-to-succeed-in-life-new-research-recommends-these-six-short-words', destination: '/affirmations/why-affirmations-are-so-powerful', permanent: true },
      { source: '/positive-affirmations-on-new-girl-scouts-cookie', destination: '/affirmations/most-popular-affirmations', permanent: true },
      { source: '/how-affirmations-can-work-for-you', destination: '/affirmations/how-do-affirmations-work', permanent: true },
      { source: '/is-manifesting-pseudoscience-the-psychology-behind-the-practice', destination: '/manifestation/is-manifestation-scientifically-proven', permanent: true },
      { source: '/health-starts-from-within', destination: '/affirmations/health-affirmations', permanent: true },
      { source: '/health-and-wellness-3-reasons-why-self-care-is-important', destination: '/affirmations/health-affirmations', permanent: true },
      { source: '/law-of-attraction-quotes', destination: '/law-of-attraction', permanent: true },
      { source: '/how-can-visualization-be-used-to-increase-self-confidence-and-self-esteem', destination: '/visualization', permanent: true },
      { source: '/abundance-mindset-and-building-wealth', destination: '/affirmations/financial-affirmations', permanent: true },
    ];
  },
};

module.exports = nextConfig;
